import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { NavbarTop } from "./components/HomePage/NavbarMenu/Navbar";
import Footer from "./components/HomePage/footer";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased`}>
        <NavbarTop />
        {children}

        <Footer />
      </body>
    </html>
  );
}
